import hr
import partner
import hr_npwp
import hr_ktp
import hr_jamsostek
import hr_religion
import hr_family_job
import hr_family
import hr_experience
import hr_education
import hr_address
import hr_payroll_declare
import hr_extension
import employee_job
import report
import wizard
import expenses_structure
import hr_mutation_history
